# Generated by Django 3.2.4 on 2021-06-24 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('wiki_url', models.CharField(max_length=1024)),
                ('description', models.TextField()),
            ],
        ),
    ]
