# Generated by Django 3.2.4 on 2021-06-24 13:26

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_alter_animal_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Artist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('gender', models.CharField(max_length=8)),
                ('nationality', models.CharField(max_length=16)),
                ('birth_year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
                ('death_year', models.PositiveIntegerField(validators=[django.core.validators.MaxValueValidator(9999)])),
            ],
        ),
    ]
