# Generated by Django 3.2.4 on 2021-06-24 13:36

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0004_auto_20210624_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artist',
            name='birth_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
        migrations.AlterField(
            model_name='artist',
            name='death_year',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MaxValueValidator(9999)]),
        ),
    ]
